//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringsContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStringsContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.UIStringsContent", typeof(UIStringsContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anim Speed:.
        /// </summary>
        public static string AnimSpeed {
            get {
                return ResourceManager.GetString("AnimSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type:.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Size:.
        /// </summary>
        public static string BustSize {
            get {
                return ResourceManager.GetString("BustSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust X Scale:.
        /// </summary>
        public static string BustXScale {
            get {
                return ResourceManager.GetString("BustXScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Y Scale:.
        /// </summary>
        public static string BustYScale {
            get {
                return ResourceManager.GetString("BustYScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Z Scale:.
        /// </summary>
        public static string BustZScale {
            get {
                return ResourceManager.GetString("BustZScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1001 - Roegadyn Female.
        /// </summary>
        public static string c1001 {
            get {
                return ResourceManager.GetString("c1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c101 - Hyur Male.
        /// </summary>
        public static string c101 {
            get {
                return ResourceManager.GetString("c101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c104 - Hyur Male (Child).
        /// </summary>
        public static string c104 {
            get {
                return ResourceManager.GetString("c104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1101 - Lalafell Male.
        /// </summary>
        public static string c1101 {
            get {
                return ResourceManager.GetString("c1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1201 - Lalafell Female.
        /// </summary>
        public static string c1201 {
            get {
                return ResourceManager.GetString("c1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1301 - Au Ra Male.
        /// </summary>
        public static string c1301 {
            get {
                return ResourceManager.GetString("c1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1401 - Au Ra Female.
        /// </summary>
        public static string c1401 {
            get {
                return ResourceManager.GetString("c1401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1501 - Hrothgar Male.
        /// </summary>
        public static string c1501 {
            get {
                return ResourceManager.GetString("c1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1801 - Viera Female.
        /// </summary>
        public static string c1801 {
            get {
                return ResourceManager.GetString("c1801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c201 - Hyur Female.
        /// </summary>
        public static string c201 {
            get {
                return ResourceManager.GetString("c201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c301 - Highlander Male.
        /// </summary>
        public static string c301 {
            get {
                return ResourceManager.GetString("c301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c401 - Highlander Female.
        /// </summary>
        public static string c401 {
            get {
                return ResourceManager.GetString("c401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c501 - Elezen Male.
        /// </summary>
        public static string c501 {
            get {
                return ResourceManager.GetString("c501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c504 - Elezen Male (Child).
        /// </summary>
        public static string c504 {
            get {
                return ResourceManager.GetString("c504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c601 - Elezen Female.
        /// </summary>
        public static string c601 {
            get {
                return ResourceManager.GetString("c601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c604 - Elezen Female (Child).
        /// </summary>
        public static string c604 {
            get {
                return ResourceManager.GetString("c604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c701 - Miqo&apos;te Male.
        /// </summary>
        public static string c701 {
            get {
                return ResourceManager.GetString("c701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c801 - Miqo&apos;te Female.
        /// </summary>
        public static string c801 {
            get {
                return ResourceManager.GetString("c801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c804 - Miqo&apos;te Female (Child).
        /// </summary>
        public static string c804 {
            get {
                return ResourceManager.GetString("c804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c901 - Roegadyn Male.
        /// </summary>
        public static string c901 {
            get {
                return ResourceManager.GetString("c901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c9104 - Padjal Male.
        /// </summary>
        public static string c9104 {
            get {
                return ResourceManager.GetString("c9104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c9204 - Padjal Female.
        /// </summary>
        public static string c9204 {
            get {
                return ResourceManager.GetString("c9204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View X:.
        /// </summary>
        public static string CameraViewX {
            get {
                return ResourceManager.GetString("CameraViewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Y:.
        /// </summary>
        public static string CameraViewY {
            get {
                return ResourceManager.GetString("CameraViewY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Z:.
        /// </summary>
        public static string CameraViewZ {
            get {
                return ResourceManager.GetString("CameraViewZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera X Pos:.
        /// </summary>
        public static string CameraXPos {
            get {
                return ResourceManager.GetString("CameraXPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Y Pos:.
        /// </summary>
        public static string CameraYPos {
            get {
                return ResourceManager.GetString("CameraYPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Z Pos:.
        /// </summary>
        public static string CameraZPos {
            get {
                return ResourceManager.GetString("CameraZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan:.
        /// </summary>
        public static string Clan {
            get {
                return ResourceManager.GetString("Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Path:.
        /// </summary>
        public static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Muscle/Tail Size:.
        /// </summary>
        public static string EarMuscleTailSize {
            get {
                return ResourceManager.GetString("EarMuscleTailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Tail Scale:.
        /// </summary>
        public static string EarTailScale {
            get {
                return ResourceManager.GetString("EarTailScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Tail Type:.
        /// </summary>
        public static string EarTailType {
            get {
                return ResourceManager.GetString("EarTailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrows Type:.
        /// </summary>
        public static string EyebrowsType {
            get {
                return ResourceManager.GetString("EyebrowsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color (Left):.
        /// </summary>
        public static string EyeColorLeft {
            get {
                return ResourceManager.GetString("EyeColorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color (Right);.
        /// </summary>
        public static string EyeColorRight {
            get {
                return ResourceManager.GetString("EyeColorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes Type:.
        /// </summary>
        public static string EyesType {
            get {
                return ResourceManager.GetString("EyesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint/Tattoo:.
        /// </summary>
        public static string FacePaint {
            get {
                return ResourceManager.GetString("FacePaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint Color:.
        /// </summary>
        public static string FacePaintColor {
            get {
                return ResourceManager.GetString("FacePaintColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Features:.
        /// </summary>
        public static string FacialFeatures {
            get {
                return ResourceManager.GetString("FacialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Anim:.
        /// </summary>
        public static string ForceAnim {
            get {
                return ResourceManager.GetString("ForceAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Tag:.
        /// </summary>
        public static string FreeCompanyTag {
            get {
                return ResourceManager.GetString("FreeCompanyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Tag.
        /// </summary>
        public static string FreeCompanyTagWaterMark {
            get {
                return ResourceManager.GetString("FreeCompanyTagWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Pos.
        /// </summary>
        public static string FreezePos {
            get {
                return ResourceManager.GetString("FreezePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Rot.
        /// </summary>
        public static string FreezeRot {
            get {
                return ResourceManager.GetString("FreezeRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color:.
        /// </summary>
        public static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyle:.
        /// </summary>
        public static string Hairstyle {
            get {
                return ResourceManager.GetString("Hairstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Type:.
        /// </summary>
        public static string HeadType {
            get {
                return ResourceManager.GetString("HeadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights:.
        /// </summary>
        public static string Highlights {
            get {
                return ResourceManager.GetString("Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Anim:.
        /// </summary>
        public static string IdleAnim {
            get {
                return ResourceManager.GetString("IdleAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Type:.
        /// </summary>
        public static string JawType {
            get {
                return ResourceManager.GetString("JawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Icon:.
        /// </summary>
        public static string JobIcon {
            get {
                return ResourceManager.GetString("JobIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbal/Tattoo Color:.
        /// </summary>
        public static string LimbalOrTattoo {
            get {
                return ResourceManager.GetString("LimbalOrTattoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lips Color/Fur Pattern:.
        /// </summary>
        public static string LipColor {
            get {
                return ResourceManager.GetString("LipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Facial Animation:.
        /// </summary>
        public static string LockFacialAnimation {
            get {
                return ResourceManager.GetString("LockFacialAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model List.
        /// </summary>
        public static string ModelList {
            get {
                return ResourceManager.GetString("ModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type:.
        /// </summary>
        public static string ModelType {
            get {
                return ResourceManager.GetString("ModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Type:.
        /// </summary>
        public static string MouthType {
            get {
                return ResourceManager.GetString("MouthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle Tone:.
        /// </summary>
        public static string MuscleTone {
            get {
                return ResourceManager.GetString("MuscleTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameWaterMark {
            get {
                return ResourceManager.GetString("NameWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Type:.
        /// </summary>
        public static string NoseType {
            get {
                return ResourceManager.GetString("NoseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Scale:.
        /// </summary>
        public static string OverallScale {
            get {
                return ResourceManager.GetString("OverallScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race:.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Appearance.
        /// </summary>
        public static string RandomizeAppearance {
            get {
                return ResourceManager.GetString("RandomizeAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime Rotation:.
        /// </summary>
        public static string RealtimeRotation {
            get {
                return ResourceManager.GetString("RealtimeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XYZ Pos:.
        /// </summary>
        public static string RelativeXYZPos {
            get {
                return ResourceManager.GetString("RelativeXYZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XYZ Rot:.
        /// </summary>
        public static string RelativeXYZRot {
            get {
                return ResourceManager.GetString("RelativeXYZRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Sliders:.
        /// </summary>
        public static string RotationSliders {
            get {
                return ResourceManager.GetString("RotationSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skintone:.
        /// </summary>
        public static string Skintone {
            get {
                return ResourceManager.GetString("Skintone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Actor is ???.
        /// </summary>
        public static string TargetActorIs {
            get {
                return ResourceManager.GetString("TargetActorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency:.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Type:.
        /// </summary>
        public static string VoiceType {
            get {
                return ResourceManager.GetString("VoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Position:.
        /// </summary>
        public static string XPos {
            get {
                return ResourceManager.GetString("XPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Rotation:.
        /// </summary>
        public static string XRot {
            get {
                return ResourceManager.GetString("XRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Position:.
        /// </summary>
        public static string YPos {
            get {
                return ResourceManager.GetString("YPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Rotation:.
        /// </summary>
        public static string YRot {
            get {
                return ResourceManager.GetString("YRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Position:.
        /// </summary>
        public static string ZPos {
            get {
                return ResourceManager.GetString("ZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Rotation:.
        /// </summary>
        public static string ZRot {
            get {
                return ResourceManager.GetString("ZRot", resourceCulture);
            }
        }
    }
}
