//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringsContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStringsContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.UIStringsContent", typeof(UIStringsContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anim Speed:.
        /// </summary>
        public static string AnimSpeed {
            get {
                return ResourceManager.GetString("AnimSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Animation Speed of the selected actor..
        /// </summary>
        public static string AnimSpeedToolTip {
            get {
                return ResourceManager.GetString("AnimSpeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Body Type of the selected actor..
        /// </summary>
        public static string BodyToolTip {
            get {
                return ResourceManager.GetString("BodyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type:.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Size:.
        /// </summary>
        public static string BustSize {
            get {
                return ResourceManager.GetString("BustSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Bust Size of the selected actor..
        /// </summary>
        public static string BustSizeToolTip {
            get {
                return ResourceManager.GetString("BustSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust X Scale:.
        /// </summary>
        public static string BustXScale {
            get {
                return ResourceManager.GetString("BustXScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the X Scale of the selected actors Bust.&amp;#xD;&amp;#xA;&amp;#x2022; This option is Female only..
        /// </summary>
        public static string BustXScaleToolTip {
            get {
                return ResourceManager.GetString("BustXScaleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Y Scale:.
        /// </summary>
        public static string BustYScale {
            get {
                return ResourceManager.GetString("BustYScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Y Scale of the selected actors Bust.&amp;#xD;&amp;#xA;&amp;#x2022; This option is Female only..
        /// </summary>
        public static string BustYScaleToolTip {
            get {
                return ResourceManager.GetString("BustYScaleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust Z Scale:.
        /// </summary>
        public static string BustZScale {
            get {
                return ResourceManager.GetString("BustZScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Z Scale of the selected actors Bust.&amp;#xD;&amp;#xA;&amp;#x2022; This option is Female only..
        /// </summary>
        public static string BustZScaleToolTip {
            get {
                return ResourceManager.GetString("BustZScaleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1001 - Roegadyn Female.
        /// </summary>
        public static string c1001 {
            get {
                return ResourceManager.GetString("c1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c101 - Hyur Male.
        /// </summary>
        public static string c101 {
            get {
                return ResourceManager.GetString("c101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c104 - Hyur Male (Child).
        /// </summary>
        public static string c104 {
            get {
                return ResourceManager.GetString("c104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1101 - Lalafell Male.
        /// </summary>
        public static string c1101 {
            get {
                return ResourceManager.GetString("c1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1201 - Lalafell Female.
        /// </summary>
        public static string c1201 {
            get {
                return ResourceManager.GetString("c1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1301 - Au Ra Male.
        /// </summary>
        public static string c1301 {
            get {
                return ResourceManager.GetString("c1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1401 - Au Ra Female.
        /// </summary>
        public static string c1401 {
            get {
                return ResourceManager.GetString("c1401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1501 - Hrothgar Male.
        /// </summary>
        public static string c1501 {
            get {
                return ResourceManager.GetString("c1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1801 - Viera Female.
        /// </summary>
        public static string c1801 {
            get {
                return ResourceManager.GetString("c1801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c201 - Hyur Female.
        /// </summary>
        public static string c201 {
            get {
                return ResourceManager.GetString("c201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c301 - Highlander Male.
        /// </summary>
        public static string c301 {
            get {
                return ResourceManager.GetString("c301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c401 - Highlander Female.
        /// </summary>
        public static string c401 {
            get {
                return ResourceManager.GetString("c401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c501 - Elezen Male.
        /// </summary>
        public static string c501 {
            get {
                return ResourceManager.GetString("c501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c504 - Elezen Male (Child).
        /// </summary>
        public static string c504 {
            get {
                return ResourceManager.GetString("c504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c601 - Elezen Female.
        /// </summary>
        public static string c601 {
            get {
                return ResourceManager.GetString("c601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c604 - Elezen Female (Child).
        /// </summary>
        public static string c604 {
            get {
                return ResourceManager.GetString("c604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c701 - Miqo&apos;te Male.
        /// </summary>
        public static string c701 {
            get {
                return ResourceManager.GetString("c701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c801 - Miqo&apos;te Female.
        /// </summary>
        public static string c801 {
            get {
                return ResourceManager.GetString("c801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c804 - Miqo&apos;te Female (Child).
        /// </summary>
        public static string c804 {
            get {
                return ResourceManager.GetString("c804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c901 - Roegadyn Male.
        /// </summary>
        public static string c901 {
            get {
                return ResourceManager.GetString("c901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c9104 - Padjal Male.
        /// </summary>
        public static string c9104 {
            get {
                return ResourceManager.GetString("c9104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c9204 - Padjal Female.
        /// </summary>
        public static string c9204 {
            get {
                return ResourceManager.GetString("c9204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View X:.
        /// </summary>
        public static string CameraViewX {
            get {
                return ResourceManager.GetString("CameraViewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Y:.
        /// </summary>
        public static string CameraViewY {
            get {
                return ResourceManager.GetString("CameraViewY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Z:.
        /// </summary>
        public static string CameraViewZ {
            get {
                return ResourceManager.GetString("CameraViewZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera X Pos:.
        /// </summary>
        public static string CameraXPos {
            get {
                return ResourceManager.GetString("CameraXPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Y Pos:.
        /// </summary>
        public static string CameraYPos {
            get {
                return ResourceManager.GetString("CameraYPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Z Pos:.
        /// </summary>
        public static string CameraZPos {
            get {
                return ResourceManager.GetString("CameraZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan:.
        /// </summary>
        public static string Clan {
            get {
                return ResourceManager.GetString("Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Clan of the selected actor..
        /// </summary>
        public static string ClanToolTip {
            get {
                return ResourceManager.GetString("ClanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Path:.
        /// </summary>
        public static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Data Path of the selected entity. &amp;#xD;&amp;#xA;This will allow you use the animations of other Races or Genders.&amp;#xD;&amp;#xA;&amp;#x2022; Does not require an Actor Refresh, and can be used in and out of GPose.&amp;#xD;&amp;#xA;&amp;#x2022; The entity&apos;s skeleton will be morphed to fit the selected race. This stretching or shrinking is unavoidable.&amp;#xD;&amp;#xA;&amp;#x2022; You can use Actor Refresh if you want to become an abomination for fun..
        /// </summary>
        public static string DataPathToolTip {
            get {
                return ResourceManager.GetString("DataPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Muscle/Tail Size:.
        /// </summary>
        public static string EarMuscleTailSize {
            get {
                return ResourceManager.GetString("EarMuscleTailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Ear, Muscle, and Tail Size of the selected actor..
        /// </summary>
        public static string EarMuscleTailSizeToolTip {
            get {
                return ResourceManager.GetString("EarMuscleTailSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Tail Scale:.
        /// </summary>
        public static string EarTailScale {
            get {
                return ResourceManager.GetString("EarTailScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Ear and Tail Scale of the selected actor..
        /// </summary>
        public static string EarTailScaleToolTip {
            get {
                return ResourceManager.GetString("EarTailScaleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ear/Tail Type:.
        /// </summary>
        public static string EarTailType {
            get {
                return ResourceManager.GetString("EarTailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Ear and Tail of the selected actor..
        /// </summary>
        public static string EarTailTypeToolTip {
            get {
                return ResourceManager.GetString("EarTailTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Eyebrows Type of the selected actor..
        /// </summary>
        public static string EyeBrowsToolTip {
            get {
                return ResourceManager.GetString("EyeBrowsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrows Type:.
        /// </summary>
        public static string EyebrowsType {
            get {
                return ResourceManager.GetString("EyebrowsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color (Left):.
        /// </summary>
        public static string EyeColorLeft {
            get {
                return ResourceManager.GetString("EyeColorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Left Eye Color of the selected actor..
        /// </summary>
        public static string EyeColorLeftToolTip {
            get {
                return ResourceManager.GetString("EyeColorLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color (Right);.
        /// </summary>
        public static string EyeColorRight {
            get {
                return ResourceManager.GetString("EyeColorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Right Eye Color of the selected actor..
        /// </summary>
        public static string EyeColorRightToolTip {
            get {
                return ResourceManager.GetString("EyeColorRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes Type:.
        /// </summary>
        public static string EyesType {
            get {
                return ResourceManager.GetString("EyesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Eyes Type of the selected actor..
        /// </summary>
        public static string EyeTypeToolTip {
            get {
                return ResourceManager.GetString("EyeTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint/Tattoo:.
        /// </summary>
        public static string FacePaint {
            get {
                return ResourceManager.GetString("FacePaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint Color:.
        /// </summary>
        public static string FacePaintColor {
            get {
                return ResourceManager.GetString("FacePaintColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Face Paint Color of the selected actor..
        /// </summary>
        public static string FacePaintColorToolTip {
            get {
                return ResourceManager.GetString("FacePaintColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Face Paint and Tattoos of the selected actor..
        /// </summary>
        public static string FacePaintToolTip {
            get {
                return ResourceManager.GetString("FacePaintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Features:.
        /// </summary>
        public static string FacialFeatures {
            get {
                return ResourceManager.GetString("FacialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Facial Features of the selected actor..
        /// </summary>
        public static string FacialFeaturesToolTip {
            get {
                return ResourceManager.GetString("FacialFeaturesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Anim:.
        /// </summary>
        public static string ForceAnim {
            get {
                return ResourceManager.GetString("ForceAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the selected entity to perform an animation.&amp;#xD;&amp;#xA;&amp;#x2022; This can only be used in GPose.&amp;#xD;&amp;#xA;&amp;#x2022; In order to use this, you need to do a non-looping emote, suchs as /wave before entering GPose.&amp;#xD;&amp;#xA;&amp;#x2022; Some animations have a specific race/gender requirement in order to perform. You may need to use a different Data Path if your character is just twitching.&amp;#xD;&amp;#xA;&amp;#x2022; Does not work on NPCs!.
        /// </summary>
        public static string ForceAnimToolTip {
            get {
                return ResourceManager.GetString("ForceAnimToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Tag:.
        /// </summary>
        public static string FreeCompanyTag {
            get {
                return ResourceManager.GetString("FreeCompanyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Tag.
        /// </summary>
        public static string FreeCompanyTagWaterMark {
            get {
                return ResourceManager.GetString("FreeCompanyTagWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Free Company Tag of the selected actor..
        /// </summary>
        public static string FreeCompanyToolTip {
            get {
                return ResourceManager.GetString("FreeCompanyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Pos.
        /// </summary>
        public static string FreezePos {
            get {
                return ResourceManager.GetString("FreezePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezes the position of the selected entity.&amp;#xD;&amp;#xA;&amp;#x2022; This is useful for moving entities in GPose, as it will prevent them from snapping back to their original position when their emote changes or you use face camera.&amp;#xD;&amp;#xA;&amp;#x2022; Make sure to press this button again before clicking or tabbing to a new entity, or it will snap them to the same position..
        /// </summary>
        public static string FreezePosToolTip {
            get {
                return ResourceManager.GetString("FreezePosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Rot.
        /// </summary>
        public static string FreezeRot {
            get {
                return ResourceManager.GetString("FreezeRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezes the rotation of the selected entity.&amp;#xD;&amp;#xA;&amp;#x2022; This is useful in conjunction with Freeze Pos for preserving the position and rotation of an entity in GPose.&amp;#xD;&amp;#xA;&amp;#x2022; You can use this along with the &apos;Face Camera&apos; toggle in-game (Default: Space Bar) to turn the entity&apos;s head without turning the entire body.&amp;#xD;&amp;#xA;&amp;#x2022; Same as Freeze Pos, make sure to toggle off Freeze Rot before switching entities in GPose. &amp;#xD;&amp;#xA;&amp;#x2022; Required for using Numerical direct input or Rotatio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FreezeRotToolTip {
            get {
                return ResourceManager.GetString("FreezeRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Gender of the selected actor..
        /// </summary>
        public static string GenderToolTip {
            get {
                return ResourceManager.GetString("GenderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color:.
        /// </summary>
        public static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Hair Color of the selected actor..
        /// </summary>
        public static string HairColorToolTip {
            get {
                return ResourceManager.GetString("HairColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyle:.
        /// </summary>
        public static string Hairstyle {
            get {
                return ResourceManager.GetString("Hairstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Hairstyle of the selected actor..
        /// </summary>
        public static string HairStyleToolTip {
            get {
                return ResourceManager.GetString("HairStyleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Type:.
        /// </summary>
        public static string HeadType {
            get {
                return ResourceManager.GetString("HeadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Head Type of the selected actor..
        /// </summary>
        public static string HeadTypeToolTip {
            get {
                return ResourceManager.GetString("HeadTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Height of the selected actor..
        /// </summary>
        public static string HeightToolTip {
            get {
                return ResourceManager.GetString("HeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles Highlights for the selected actor..
        /// </summary>
        public static string HighLightButtonToolTip {
            get {
                return ResourceManager.GetString("HighLightButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights:.
        /// </summary>
        public static string Highlights {
            get {
                return ResourceManager.GetString("Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Highlights Color of the selected actor..
        /// </summary>
        public static string HighlightsToolTip {
            get {
                return ResourceManager.GetString("HighlightsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Anim:.
        /// </summary>
        public static string IdleAnim {
            get {
                return ResourceManager.GetString("IdleAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Idle Animation of the selected entity.&amp;#xD;&amp;#xA;&amp;#x2022; This can be used both in and out of GPose.&amp;#xD;&amp;#xA;&amp;#x2022; If you plan to use this in GPose, you will need to sit/stand, then use /cpose until your Idle Anim reads &apos;3&apos;&amp;#xD;&amp;#xA;&amp;#x2022; This can be used on Pets, Minions, Chocobos and most NPCs!.
        /// </summary>
        public static string IdleAnimToolTip {
            get {
                return ResourceManager.GetString("IdleAnimToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Type:.
        /// </summary>
        public static string JawType {
            get {
                return ResourceManager.GetString("JawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Jaw Type of the selected actor..
        /// </summary>
        public static string JawTypeToolTip {
            get {
                return ResourceManager.GetString("JawTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Icon:.
        /// </summary>
        public static string JobIcon {
            get {
                return ResourceManager.GetString("JobIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Job Icon of the selected party member in your party list..
        /// </summary>
        public static string JobIconToolTip {
            get {
                return ResourceManager.GetString("JobIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbal/Tattoo Color:.
        /// </summary>
        public static string LimbalOrTattoo {
            get {
                return ResourceManager.GetString("LimbalOrTattoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Limbal Ring and Tattoo Color of the selected actor..
        /// </summary>
        public static string LimbalOrTattooToolTip {
            get {
                return ResourceManager.GetString("LimbalOrTattooToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lips Color/Fur Pattern:.
        /// </summary>
        public static string LipColor {
            get {
                return ResourceManager.GetString("LipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Lips Color and Fur Pattern of the selected actor..
        /// </summary>
        public static string LipColorToolTip {
            get {
                return ResourceManager.GetString("LipColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Facial Animation:.
        /// </summary>
        public static string LockFacialAnimation {
            get {
                return ResourceManager.GetString("LockFacialAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks the Facial Animation of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; To properly lock the facial animation of the selected actor, you need to toggle this on, freeze the option, and then set Anim Speed to Zero..
        /// </summary>
        public static string LockFacialAnimationToolTip {
            get {
                return ResourceManager.GetString("LockFacialAnimationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model List.
        /// </summary>
        public static string ModelList {
            get {
                return ResourceManager.GetString("ModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type:.
        /// </summary>
        public static string ModelType {
            get {
                return ResourceManager.GetString("ModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a flyout menu on the right side that allows you to search for Monsters, Demi-Humans, Prop Entities and Entity-Based Effects.&amp;#xD;&amp;#xA;&amp;#x2022; Some NPCs are found under this selection because they are classified as Demi-Humans, such as Beast Tribes, Zenos, Thordan/Knights, etc.&amp;#xD;&amp;#xA;&amp;#x2022; If you become invisible after changing to a Demi-Human, change all of your Equipment to Base 0, Variant 0. If this doesn&apos;t work, try 1,0 or 1,1..
        /// </summary>
        public static string ModelTypeButtonToolTip {
            get {
                return ResourceManager.GetString("ModelTypeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Model Type of the selected actor..
        /// </summary>
        public static string ModelTypeToolTip {
            get {
                return ResourceManager.GetString("ModelTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Type:.
        /// </summary>
        public static string MouthType {
            get {
                return ResourceManager.GetString("MouthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Mouth Type of the selected actor..
        /// </summary>
        public static string MouthTypeToolTip {
            get {
                return ResourceManager.GetString("MouthTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle Tone:.
        /// </summary>
        public static string MuscleTone {
            get {
                return ResourceManager.GetString("MuscleTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Muscle Tone of the selected actor..
        /// </summary>
        public static string MuscleToneToolTip {
            get {
                return ResourceManager.GetString("MuscleToneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the display name of the selected actor..
        /// </summary>
        public static string NameToolTip {
            get {
                return ResourceManager.GetString("NameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameWaterMark {
            get {
                return ResourceManager.GetString("NameWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Type:.
        /// </summary>
        public static string NoseType {
            get {
                return ResourceManager.GetString("NoseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Nose Type of the selected actor..
        /// </summary>
        public static string NoseTypeToolTip {
            get {
                return ResourceManager.GetString("NoseTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Scale:.
        /// </summary>
        public static string OverallScale {
            get {
                return ResourceManager.GetString("OverallScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Overall Scale of the selected actor..
        /// </summary>
        public static string OverallScaleToolTip {
            get {
                return ResourceManager.GetString("OverallScaleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race:.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Race of the selected actor..
        /// </summary>
        public static string RaceToolTip {
            get {
                return ResourceManager.GetString("RaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Appearance.
        /// </summary>
        public static string RandomizeAppearance {
            get {
                return ResourceManager.GetString("RandomizeAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will create a random appearance..
        /// </summary>
        public static string RandomizeAppearanceToolTip {
            get {
                return ResourceManager.GetString("RandomizeAppearanceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime Rotation:.
        /// </summary>
        public static string RealtimeRotation {
            get {
                return ResourceManager.GetString("RealtimeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your mouse buttons to control the cube. &amp;#xD;&amp;#xA;All rotations are relative to the direction that the entity is currently facing.&amp;#xD;&amp;#xA;&amp;#x2022; RMB controls X-axis rotation.&amp;#xD;&amp;#xA;&amp;#x2022; LMB controls Y-axis rotation.&amp;#xD;&amp;#xA;&amp;#x2022; MMB controls Z-axis rotation..
        /// </summary>
        public static string RealTimeRotationToolTip {
            get {
                return ResourceManager.GetString("RealTimeRotationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XYZ Pos:.
        /// </summary>
        public static string RelativeXYZPos {
            get {
                return ResourceManager.GetString("RelativeXYZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This toggle will make all XYZ movements relative to the entity being targeted, and not absolute based on the gameworld.&amp;#xD;&amp;#xA;&amp;#x2022; This setting is defaulted to on, and its state is saved between sessions..
        /// </summary>
        public static string RelativeXYZPosToolTip {
            get {
                return ResourceManager.GetString("RelativeXYZPosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XYZ Rot:.
        /// </summary>
        public static string RelativeXYZRot {
            get {
                return ResourceManager.GetString("RelativeXYZRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This toggle will make all XYZ rotations relative to the entity being targeted, and not absolute based on the gameworld.&amp;#xD;&amp;#xA;&amp;#x2022; This setting is defaulted to on, and its state is saved between sessions. &amp;#xD;&amp;#xA;&amp;#x2022; Only affects the Realtime Rotation Cube..
        /// </summary>
        public static string RelativeXYZRotToolTip {
            get {
                return ResourceManager.GetString("RelativeXYZRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Sliders:.
        /// </summary>
        public static string RotationSliders {
            get {
                return ResourceManager.GetString("RotationSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This toggle will switch between Rotation Sliders and Numerical direct input.&amp;#xD;&amp;#xA;&amp;#x2022; This setting is defaulted to on, and its state is saved between sessions.&amp;#xD;&amp;#xA;&amp;#x2022; Turning it off will turn the XYZ Rotation sliders into numerical values.&amp;#xD;&amp;#xA;&amp;#x2022; Each input will accept a value between 0 and 360.&amp;#xD;&amp;#xA;&amp;#x2022; Both Rotation Sliders and Numerical direct input require Rotation to be frozen..
        /// </summary>
        public static string RotationSlidersToolTip {
            get {
                return ResourceManager.GetString("RotationSlidersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skintone:.
        /// </summary>
        public static string Skintone {
            get {
                return ResourceManager.GetString("Skintone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Skintone of the selected actor..
        /// </summary>
        public static string SkinToneToolTip {
            get {
                return ResourceManager.GetString("SkinToneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Actor is ???.
        /// </summary>
        public static string TargetActorIs {
            get {
                return ResourceManager.GetString("TargetActorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Title of the selected actor..
        /// </summary>
        public static string TitleToolTip {
            get {
                return ResourceManager.GetString("TitleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency:.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the transparency of the selected entity.&amp;#xD;&amp;#xA;&amp;#x2022; Reducing the transparency of an actor does not affect their main or offhand weapons. You can set the XYZ scale of their weapons to 0 in the Equipment tab.&amp;#xD;&amp;#xA;&amp;#x2022; Setting this to 0 for an entity in GPose can cause the system to forget that they&apos;re targetable. If you plan to still use them, set it to 0.03..
        /// </summary>
        public static string TransparencyToolTip {
            get {
                return ResourceManager.GetString("TransparencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Type:.
        /// </summary>
        public static string VoiceType {
            get {
                return ResourceManager.GetString("VoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Voice Type of the selected actor..
        /// </summary>
        public static string VoiceTypeToolTip {
            get {
                return ResourceManager.GetString("VoiceTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Position:.
        /// </summary>
        public static string XPos {
            get {
                return ResourceManager.GetString("XPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the X Position of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose..
        /// </summary>
        public static string XPosToolTip {
            get {
                return ResourceManager.GetString("XPosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Rotation:.
        /// </summary>
        public static string XRot {
            get {
                return ResourceManager.GetString("XRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the X Rotation of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose.&amp;#xD;&amp;#xA;&amp;#x2022; Both Rotation Sliders and Numerical direct input require Rotation to be frozen..
        /// </summary>
        public static string XRotToolTip {
            get {
                return ResourceManager.GetString("XRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Position:.
        /// </summary>
        public static string YPos {
            get {
                return ResourceManager.GetString("YPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Y Position of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose..
        /// </summary>
        public static string YPosToolTip {
            get {
                return ResourceManager.GetString("YPosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Rotation:.
        /// </summary>
        public static string YRot {
            get {
                return ResourceManager.GetString("YRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Y Rotation of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose.&amp;#xD;&amp;#xA;&amp;#x2022; Both Rotation Sliders and Numerical direct input require Rotation to be frozen..
        /// </summary>
        public static string YRotToolTip {
            get {
                return ResourceManager.GetString("YRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Position:.
        /// </summary>
        public static string ZPos {
            get {
                return ResourceManager.GetString("ZPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Z Position of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose..
        /// </summary>
        public static string ZPosToolTip {
            get {
                return ResourceManager.GetString("ZPosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Rotation:.
        /// </summary>
        public static string ZRot {
            get {
                return ResourceManager.GetString("ZRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Z Rotation of the selected actor.&amp;#xD;&amp;#xA;&amp;#x2022; You may need to Freeze the animations of your actor to properly apply this in GPose.&amp;#xD;&amp;#xA;&amp;#x2022; Both Rotation Sliders and Numerical direct input require Rotation to be frozen..
        /// </summary>
        public static string ZRotToolTip {
            get {
                return ResourceManager.GetString("ZRotToolTip", resourceCulture);
            }
        }
    }
}
